### ISSUE TITLE
Feature Request: SOD-123

### ISSUE THREAD

**Issue by fi0** [swanmatch/MxLEDBitPCB#6]
Thank you for your great work!
Can you add a diode footprint that supports both through hole and SOD-123 please?

**Comment by swanmatch** [comment]
Choc does not support through holes due to space limitations, only SOD123.
suxen and Container have pads for SOD123, but due to space limitations, one pad is shared with TH, which makes the implementation a bit trickier.
Basically, a through-hole diode is recommended because the legs of the cut diode can be used for wiring.


Project | Switch | Socket | LED | THDiode | SOD-123 |
-|-|-|-|-|-
Nexus | MX | No | SK6812MINI | Yes | No |
Altana | MX | Yes | SK6812MINI | Yes | No |
Suxen | MX | No | YS-SK6812MINI | Yes | Yes |
Container | MX | Yes | YS-SK6812MINI | Yes | Yes |
Choc | KailhLowProfile | No | YS-SK6812MINI | No | Yes |

**Comment by fi0** [comment]
Thank you for the explanation!! 😄
